version: 2.1

orbs:
python: circleci/python@2.1.1

jobs:
build_and_test:
executor: python/default
steps:
- checkout
- python/load-cache
- python/install-deps
- python/save-cache
- python/dist
- python/test:
pytest: true
- run:
command: |
flake8 --exclude=venv*, __init__.py --statistics
name: Inspect PEP8 (flake8)

workflows:
main:
jobs:
- build_and_test
